PL_Web/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using BL;
using ET;
namespace PL_Web.Controllers
{
    public class AlumnoController : Controller
    {
        private AlumnoBL alumnoBL = new AlumnoBL();
        private RolBL rolBL = new RolBL();
        private GrupoBL grupoBL = new GrupoBL();

        // Listado de todos los alumnos
        public ActionResult Index()
        {
            return View(alumnoBL.Listar());
        }


        //vista de editar y agregar solo le pasamos el parametro
        public ActionResult Editar(int id = 0)
        {
            ViewBag.Roles = rolBL.Listar();
            ViewBag.Grupos = grupoBL.Listar();
            return View(id == 0 ? new Alumno() : alumnoBL.Obtener(id));
        }


        //guardar alumnos si no lo edita
        public ActionResult Guardar(Alumno user)
        {
            var r = user.id > 0 ?
                   alumnoBL.Actualizar(user) : alumnoBL.Registrar(user);

            if (!r)
            {
                ViewBag.Mensaje = "Ocurrio un error inesperado";
                return View("~/View/Shared/_Mensaje.cshtml");
            }
            return RedirectToAction("Index");
        }

        
        public ActionResult Eliminar(int id)
        {
            var r = alumnoBL.Eliminar(id);
            if (!r)
            {
                ViewBag.Mensaje = "Ocurrio un error inesperado";
                return View("~/Views/Shared/_Mensaje.cshtml");
            }
            return RedirectToAction("Index");
        }
    }
}

PL_Web/Controllers/GrupoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using BL;
using ET;
namespace PL_Web.Controllers
{
    public class GrupoController : Controller
    {
        public GrupoBL grupoBL = new GrupoBL();

        // GET: Grupo
        public ActionResult Index()
        {
            return View(grupoBL.Listar());
        }


        public ActionResult Editar(int id = 0)
        {
            ViewBag.Grupos = grupoBL.Listar();
            return View(id == 0 ? new Grupo() : grupoBL.Obtener(id));
        }


        public ActionResult Guardar(Grupo grupo)
        {
            var r = grupo.id > 0 ?
                    grupoBL.Actualizar(grupo) :
                    grupoBL.Registrar(grupo);
            if (!r)
            {
                ViewBag.Mensaje = "Ocurrio un error inesperado";
                return View("~/Views/Shared/_Mensajes.cshtml");
            }
            return RedirectToAction("Index");
        }



        public ActionResult Eliminar(int id)
        {
            var r = grupoBL.Eliminar(id);
            if (!r)
            {
                ViewBag.Mensaje = "Ocurrio un error inesperado";
                return View("~/Views/Shared/_Mensajes.cshtml");
            }
            return RedirectToAction("Index");
        }
    }
}

PL_Web/Controllers/OtrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BL;
using ET;
namespace PL_Web.Controllers
{
    
    public class OtrosController : Controller
    {
        private AlumnoBL alumnoBL = new AlumnoBL();
        private RolBL rolBL = new RolBL();
        // Listado de  Otros
        public ActionResult Index()
        {
            return View(alumnoBL.Listar3());
        }

        //vista de editar y agregar solo le pasamos el parametro
        public ActionResult Editar(int id = 0)
        {
            ViewBag.Roles = rolBL.Listar();
            return View(id == 0 ? new Alumno() : alumnoBL.Obtener(id));
        }


        //guardar alumnos si no lo edita
        public ActionResult Guardar(Alumno user)
        {
            var r = user.id > 0 ?
                   alumnoBL.Actualizar(user) : alumnoBL.Registrar(user);

            if (!r)
            {
                ViewBag.Mensaje = "Ocurrio un error inesperado";
                return View("~/View/Shared/_Mensaje.cshtml");
            }
            return RedirectToAction("../");
        }


        public ActionResult Eliminar(int id)
        {
            var r = alumnoBL.Eliminar(id);
            if (!r)
            {
                ViewBag.Mensaje = "Ocurrio un error inesperado";
                return View("~/Views/Shared/_Mensaje.cshtml");
            }
            return RedirectToAction("../");
        }
    }
}

PL_Web/Controllers/ProfesoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



using BL;
using ET;
namespace PL_Web.Controllers
{
    public class ProfesoresController : Controller
    {
        private AlumnoBL alumnoBL = new AlumnoBL();
        private RolBL rolBL = new RolBL();

        // Listado de todos los profesores
        public ActionResult Index()
        {
            return View(alumnoBL.Listar2());
        }


        //vista de editar y agregar solo le pasamos el parametro
        public ActionResult Editar(int id = 0)
        {
            ViewBag.Roles = rolBL.Listar();
            return View(id == 0 ? new Alumno() : alumnoBL.Obtener(id));
        }


        //guardar alumnos si no lo edita
        public ActionResult Guardar(Alumno user)
        {
            var r = user.id > 0 ?
                   alumnoBL.Actualizar(user) : alumnoBL.Registrar(user);

            if (!r)
            {
                ViewBag.Mensaje = "Ocurrio un error inesperado";
                return View("~/View/Shared/_Mensaje.cshtml");
            }
            return RedirectToAction("../");
        }


        public ActionResult Eliminar(int id)
        {
            var r = alumnoBL.Eliminar(id);
            if (!r)
            {
                ViewBag.Mensaje = "Ocurrio un error inesperado";
                return View("~/Views/Shared/_Mensaje.cshtml");
            }
            return RedirectToAction("../");
        }
    }
}

PL_Web/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using BL;
using ET;
namespace PL_Web.Controllers
{
    public class RolController : Controller
    {
        //private Rol rol = new Rol();
        private RolBL rolBL = new RolBL();

        // GET: Rol
        public ActionResult Index()
        {
            return View(rolBL.Listar());
        }



        public ActionResult Editar(int id = 0)
        {
            ViewBag.Roles = rolBL.Listar();
            return View(id == 0 ? new Rol() : rolBL.Obtener(id));
        }



        public ActionResult Guardar(Rol rol)
        {
            var r = rol.id > 0 ?
                    rolBL.Actualizar(rol) :
                    rolBL.Registrar(rol);

            if (!r)
            {
                ViewBag.Mensaje = "Ocurrio un error inseperado";
                return View("~/Views/Shared/_Mensajes.cshtml");
            }
            return RedirectToAction("Index");
        }

        public ActionResult Eliminar(int id)
        {
            var r = rolBL.Eliminar(id);
            if (!r)
            {
                ViewBag.Mensaje = "Ocurrio un error inesperado";
                return View("~/Views/Shared/_Mensajes.cshtml");
            }
            return RedirectToAction("Index");
        }
    }
}

PL_Web/Views/Alumno/Editar.cshtml
@model ET.Alumno
@{
    ViewBag.Title = "Editar";
    List<ET.Rol> roles = ViewBag.Roles;
    List<ET.Grupo> grupos = ViewBag.Grupos;
}

<h2>Registrar y Editar</h2>


@using (Html.BeginForm("guardar", "Alumno", FormMethod.Post))
{
<div class="container">
    @Html.HiddenFor(c => c.id)

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre)
        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Apellido)
        @Html.TextBoxFor(model => model.Apellido, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Rol)
        <select name="Rol_id">
            @foreach (var r in roles)
            {
                <option @(r.id == Model.Rol_id ? "selected" : "") value="@r.id">@r.Puesto</option>
            }
        </select>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Grupo)
        <select name="Grupo_id">
            @foreach (var r in grupos)
            {
                <option @(r.id == Model.Grupo_id ? "selected" : "") value="@r.id">@r.Grupos</option>
            }
        </select>
    </div>
    <div class="form-group">
        <button type="submit">Enviar</button>
    </div>
</div>
}

PL_Web/Views/Alumno/Index.cshtml
@model List<ET.Alumno>
@{
    ViewBag.Title = "Index";
}

<h2>Alumnos</h2>
<div style="float:right; margin: 1rem 0rem 1rem 0rem;  ">
    <a class="btn btn-primary" href="~/Alumno/Editar">Alumno nuevo</a>
</div>
<div class="container" style="text-align:center;">
    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <td>Nombre</td>
                <td>Apellido</td>
                <td>Rol</td>
                <td>Grupo</td>
                <td>Materia</td>
                <td>Operaciones</td>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
            <tr>
                <td>@item.Nombre</td>
                <td>@item.Apellido</td>
                <td>@item.Rol.Puesto</td>
                <td>@item.Grupo.Grupos</td>
                <td>@item.Grupo.Materia</td>
                <td>
                    <a class="btn btn-warning" href="~/Alumno/editar/@item.id">Editar</a>
                    <a class="btn btn-danger" onclick="return confirm('¿Esta seguro?');" href="~/Alumno/eliminar/@item.id">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>

</div>

PL_Web/Views/Grupo/Editar.cshtml
@model ET.Grupo
@{
    ViewBag.Title = "Editar";
}

<h2>Registrar y Editar</h2>

@using (Html.BeginForm("guardar", "Grupo", FormMethod.Post))
{
    <div class="container">
        @Html.HiddenFor(c => c.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Grupos)
            @Html.TextBoxFor(model => model.Grupos, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Materia)
            @Html.TextBoxFor(model => model.Materia, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <button type="submit">Enviar</button>
        </div>
    </div>
}

PL_Web/Views/Grupo/Index.cshtml
@model List<ET.Grupo>
@{
    ViewBag.Title = "Index";
}

<h2>Grupos</h2>

<div style="float:right; margin: 1rem 0rem 1rem 0rem;  ">
    <a class="btn btn-primary" href="~/Grupo/Editar">Grupo Nuevo</a>
</div>

<div class="container" style="text-align:center;">
    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <td>Grupo</td>
                <td>Materia</td>
                <td>Operaciones</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Grupos</td>
                    <td>@item.Materia</td>
                    <td>
                        <a class="btn btn-warning" href="~/Grupo/editar/@item.id">Editar</a>
                        <a class="btn btn-danger" onclick="return confirm('¿Esta seguro?');" href="~/Grupo/eliminar/@item.id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

PL_Web/Views/Otros/Index.cshtml
@model List<ET.Alumno>
@{
    ViewBag.Title = "Index";
}

<h2>Otros</h2>
<div style="float:right; margin: 1rem 0rem 1rem 0rem;  ">
    <a class="btn btn-primary" href="~/Alumno/Editar">Registro nuevo</a>
</div>
<div class="container" style="text-align:center;">
    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <td>Nombre</td>
                <td>Apellido</td>
                <td>Rol</td>
                <td>Operaciones</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Nombre</td>
                    <td>@item.Apellido</td>
                    <td>@item.Rol.Puesto</td>
                    <td>
                        <a class="btn btn-warning" href="~/Alumno/editar/@item.id">Editar</a>
                        <a class="btn btn-danger" onclick="return confirm('¿Esta seguro?');" href="~/Alumno/eliminar/@item.id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

PL_Web/Views/Profesores/Index.cshtml
@model List<ET.Alumno>
@{
    ViewBag.Title = "Index";
}

<h2>Profesores</h2>
<div style="float:right; margin: 1rem 0rem 1rem 0rem;  ">
    <a class="btn btn-primary" href="~/Alumno/Editar">Profesor Nuevo</a>
</div>
<div class="container" style="text-align:center;">
    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <td>Nombre</td>
                <td>Apellido</td>
                <td>Rol</td>
                <td>Operaciones</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Nombre</td>
                    <td>@item.Apellido</td>
                    <td>@item.Rol.Puesto</td>
                    <td>
                        <a class="btn btn-warning" href="~/Alumno/editar/@item.id">Editar</a>
                        <a class="btn btn-danger" onclick="return confirm('¿Esta seguro?');" href="~/Alumno/eliminar/@item.id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

PL_Web/Views/Rol/Editar.cshtml
@model ET.Rol
@{
    ViewBag.Title = "Editar";
}

<h2>Registrar y Editar</h2>


@using (Html.BeginForm("guardar", "Rol", FormMethod.Post))
{
    <div class="container">
        @Html.HiddenFor(x => x.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Puesto)
            @Html.TextBoxFor(model => model.Puesto, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <button type="submit">Enviar</button>
        </div>
    </div>
}

PL_Web/Views/Rol/Index.cshtml
@model List<ET.Rol>
@{
    ViewBag.Title = "Index";
}

<h2>Roles</h2>
<div style="float:right; margin: 1rem 0rem 1rem 0rem;  ">
    <a class="btn btn-primary" href="~/Rol/Editar">Rol nuevo</a>
</div>

<div class="container" style="text-align:center;">
    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <td>id</td>
                <td>Puesto</td>
                <td>Operaciones</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.id</td>
                    <td>@item.Puesto</td>
                    <td>
                        <a class="btn btn-warning" href="~/Rol/editar/@item.id">Editar</a>
                        <a class="btn btn-danger" onclick="return confirm('¿Esta seguro?');" href="~/Rol/eliminar/@item.id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

PL_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.ActionLink("Alumnos", "Index", "Alumno", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Profesores", "Index", "Profesores", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Grupos", "Index", "Grupo", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Otros", "Index", "Otros", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Roles", "Index", "Rol", new { area = "" }, new { @class = "navbar-brand" })
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="position: absolute; bottom:0px;">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

PL_Web/Views/Shared/_Mensaje.cshtml
<p>@ViewBag.Mensaje</p>